name: CI
on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Set up poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      
      - name: Install dependancies
        run: poetry install

      - name: Code Quality
        run: poetry run flake8

      - name: Test with pytest
        run: poetry run pytest
